# Hardware Setting for sequencers
# Settings for multiple sequencers or setting versions can be stored in this file
# The settings used is specified by `name`
# Software settings should go in default.toml
name: Test                                                                      # name of sequencer
Test:                                                                           # settings for a specific sequencer
  flowcells: ['A', 'B']                                                         # list of flow cell names 
  FlowCellA:
    inlet_port: 
      2: 2
      8: 3 
  FlowCellB:
    inlet_port: 
      2: 4
      8: 5
  PumpA: &pump                                                                  # &pump anchor for future reference
    com: &pumpcom
      baudrate: 9600
      timeout: 1
      address: KLOEHNAA                                                             # address identifier for communication
      prefix: /1
      suffix: "\r"
    volume:                                                                     # volume parameter for pump
      units: uL                                                                 # units of volume, optional
    flow_rate:                                                                  # flow rate parameter for pump
      units: uL/min                                                             # units of volume, optional
    steps: 48000
    barrel_volume: 250                                                          # uL
    barrels_per_lane: 8
    max_sps: 8000                                                               # max steps per second
    min_sps: 40                                                                 # min steps per second

  PumpB:
    <<: *pump                                                                   # reference settings using anchor from `PumpA`
    com:
      <<: *pumpcom
      address: KLOEHNBA
  Valve24A: &valve24                                                              # &valve anchor for future reference
    com: &valvecom
      baudrate: 9600
      timeout: 1
      address: VICIA2A                                                          # address identifier for communication
      prefix: ""
      suffix: "\r"
    port:
      valid_list: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] # list of possible values for parameter, used for validation
    safe_port: 20
  Valve24B:                                                                     # reference settings using anchor from `ValveA`
    <<: *valve24    
    com:
      <<: *valvecom                                                             
      address: VICIB2A
  Valve10A:                                                                     # &valve anchor for future reference
    com: 
      <<: *valvecom
      address: VICIA1A
    port:
      valid_list: [2,3]                                                         # list of possible values for parameter, used for validation
    safe_port: 2
  Valve10B:                                                                     # reference settings using anchor from `ValveA` 
    com:
      <<: *valvecom 
      address: VICIB1A                                                            
    port:
      valid_list: [4,5]                                                         # list of possible values for parameter, used for validation
    safe_port: 4
  XStage:
    com:
      baudrate: 9600
      timeout: 1
      address: IL000001A
      prefix: ""
      suffix: "\r"   
    spum: 1                                                                     # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    origin:                                                                     # reference step for flow cells, used in `custom_roi_factory`
      A: 100
      B: 200
    step: 100                                                                   # steps between tiles used in microscope routines
    position:
      min_val: 0
      max_val: 50000
      units: steps
  YStage:
    com:
      baudrate: 9600
      timeout: 1
      address: IL000002A
      prefix: ""
      suffix: "\r\n"   
    spum: 100                                                                   # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    origin: 300                                                                 # reference step for flow cells, used in `custom_roi_factory`
    step: 200                                                                   # steps between tiles used in microscope routines
    position:
      min_val: -7000000
      max_val: 7000000
      units: steps
    mode:
      imaging:
        gains: '5,10,5,2,0' 
        velocity: 0.15400
      moving: 
        gains: '5,10,7,1.5,0'
        velocity: 1
  TiltStage1: &tiltstage
    address: COM8, COM9                                                         # uses 2 communication addresses, FPGA Tx and FPGA Rx
    spum: 100                                                                   # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    position: &tiltposition                                                     # &tiltposition anchor for future reference
      min_val: 0
      max_val: 30000
      units: steps
  TiltStage2: *tiltstage
  TiltStage3: *tiltstage
  ZStage:
    address: TiltStage                                                          # shares communication address with `TiltStage`
    spum: 1                                                                     # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    step: 1                                                                     # steps between z planes used in microscope z-stack routiness
    position:
      min_val: 0
      max_val: 65000
      units: steps
  redLaser: 
    com:
      baudrate: 9600
      timeout: 1
      address: IL000007A
      prefix: ""
      suffix: "\r"  
    power: &red_laser                                                         # &red_laser anchor for future reference
      min_val: 0
      max_val: 400
      units: mW
  greenLaser: 
    com:
      baudrate: 9600
      timeout: 1
      address: IL000006A
      prefix: ""
      suffix: "\r"  
    power: &green_laser                                                         # &green_laser anchor for future reference
      min_val: 0
      max_val: 400 
      units: mW
  TemperatureControllerA: &fc_temp                                              # &fc_temp anchor for future reference
    address: TiltStage
    temperature:
      min_val: 4
      max_val: 60
      units: C
  TemperatureControllerB: *fc_temp                                              # reference settings using anchor from `TemperatureControllerB`
  Shutter:
    address: TiltStage
  redFilterWheel: 
    address: TiltStage
    filter: &red_filter_wheel                                                   # &red_filter_wheel anchor for future reference
      valid_list: {'home':0, 'open':1, '0.1':2, '1.0':3}
  greenFilterWheel: 
    address: TiltStage
    filter: &green_filter_wheel                                                 # &green_filter_wheel anchor for future reference
      valid_list: {'home':0, 'open':1, '0.1':2, '2.0':3}
  Camera_558_687: &camera                                                       # &camera anchor for future reference
    exposure: &camera_exposure                                                  # &camera_exposure anchor for future reference
      min_val: 0.1
      max_val: 10
      units: s
  Camera_610_740: *camera                                                       # reference settings using anchor from `Camera_558_687`                                         
# Extra validation parameters for stage beyond X, Y, Z 
# Should align with stage table in default.toml
  stage: 
    tilt1: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
    tilt2: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
    tilt3: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
# Custom validation parameters for optical settings 
# used during imaging, focusing, or exposing 
# Should align with optics table in default.toml
  optics:
    power:
      green: *green_laser                                                       # reference settings using anchor from power of `redLaser`
      red: *red_laser                                                           # reference settings using anchor from power of `greenLaser`
    exposure: 
      Camera_558_687: *camera_exposure                                          # reference settings using anchor from exposure of `Camera_558_687`
      Camera_610_740: *camera_exposure                                          # reference settings using anchor from exposure of `Camera_558_687`
    filter: 
      green: *green_filter_wheel                                                # reference settings using anchor from filter of `greenFilterWheel`
      red: *red_filter_wheel                                                    # reference settings using anchor from filter of `redFilterWheel`