# Hardware Setting for sequencers
# Settings for multiple sequencers or setting versions can be stored in this file
# The settings used is specified by `name`
# Software settings should go in default.toml
name: Test                                                                      # name of sequencer
Test:                                                                           # settings for a specific sequencer
  model: HiSeq2500
  flowcells: ['A', 'B']                                                         # list of flow cell names 
  FlowCellA:
    inlet_port: 
      2: 2
      8: 3 
  FlowCellB:
    inlet_port: 
      2: 4
      8: 5
  Microscope:
    resolution: 0.375                                                           # um/px
  Cameras:
    sensor_width: 2048                                                          # width of TDI line sensor in pixels
    sensor_height: 64                                                           # height of TDI line sensor in pixels
    exposure: &camera_exposure                                                  # &camera_exposure anchor for future reference
      min_val: 0.00002
      max_val: 1.004
      units: s
    gain:                                                       
      min_val: 0
      max_val: 15
      units: X
    save_nt: False                                                              # save images with nucleotide name instead of emission wavelength
    TDI: 
      sensor_mode_line_bundle_height: &y_step 128
    AREA: 
      sensor_mode_line_bundle_height: 64
    0:                                                                          # Camera ID 0 properties
      nucleotides: "AG"
      left_emission: 687                                                          # A
      right_emission: 558                                                         # G
      name: Camera_687_558
    1:                                                                          # Camera ID 1 properties                   
      nucleotides: "TC"  
      left_emission: 610                                                          # T
      right_emission: 740                                                         # C
      name: Camera_610_740
  PumpA: &pump                                                                  # &pump anchor for future reference
    com: &pumpcom
      baudrate: 9600
      timeout: 1
      address: KLOEHNAA                                                             # address identifier for communication
      prefix: /1
      suffix: "\r"
    volume:                                                                     # volume parameter for pump
      units: uL                                                                 # units of volume, optional
    flow_rate:                                                                  # flow rate parameter for pump
      units: uL/min                                                             # units of volume, optional
    steps: 48000
    barrel_volume: 250                                                          # uL
    barrels_per_lane: 8
    max_sps: 8000                                                               # max steps per second
    min_sps: 40                                                                 # min steps per second
  PumpB:
    <<: *pump                                                                   # reference settings using anchor from `PumpA`
    com:
      <<: *pumpcom
      address: KLOEHNBA
  Valve24A: &valve24                                                              # &valve anchor for future reference
    com: &valvecom
      baudrate: 9600
      timeout: 1
      address: VICIA2A                                                          # address identifier for communication
      prefix: ""
      suffix: "\r"
    port:
      valid_list: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] # list of possible values for parameter, used for validation
    safe_port: 20
  Valve24B:                                                                     # reference settings using anchor from `ValveA`
    <<: *valve24    
    com:
      <<: *valvecom                                                             
      address: VICIB2A
  Valve10A:                                                                     # &valve anchor for future reference
    com: 
      <<: *valvecom
      address: VICIA1A
    port:
      valid_list: [2,3]                                                         # list of possible values for parameter, used for validation
    safe_port: 2
  Valve10B:                                                                     # reference settings using anchor from `ValveA` 
    com:
      <<: *valvecom 
      address: VICIB1A                                                            
    port:
      valid_list: [4,5]                                                         # list of possible values for parameter, used for validation
    safe_port: 4
  XStage:
    com:
      baudrate: 9600
      timeout: 1
      address: IL000001A
      prefix: ""
      suffix: "\r"   
    spum: 0.4096                                                                # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    origin:                                                                     # reference step for flow cells, used in `custom_roi_factory`
      A: 17571
      B: 43310
    step: 315                                                                   # steps between tiles used in microscope routines
    position:
      min_val: 1000
      max_val: 50000
      units: steps
    echo_mode: 2                                                                # 2 = does not echo back commands
  YStage:
    com:
      baudrate: 9600
      timeout: 1
      address: IL000002A
      prefix: "1"
      suffix: "\r\n"   
    spum: 100                                                                   # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    origin: -180000                                                             # reference step for flow cells, used in `custom_roi_factory`
    step: *y_step                                                               # line bundle height for TDI imaging
    position:
      min_val: -7000000
      max_val: 7000000
      units: steps
    mode:
      imaging:
        gains: '5,10,5,2,0' 
        velocity: 0.15400
      moving: 
        gains: '5,10,7,1.5,0'
        velocity: 1
  FPGA:
    com: &fpgacom
      baudrate: 115200
      timeout: 1
      address: IL000004A
      rx_address: IL000005A
      prefix: ""
      suffix: "\n"  
  TiltStage: &tiltstage
    com:
      address: FPGA
    spum: 0.656                                                                 # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    position: &tiltposition                                                     # &tiltposition anchor for future reference
      min_val: 0
      max_val: 30000
      units: steps
    tolerance: 5   
  TiltMotor1: *tiltstage
  TiltMotor2: *tiltstage
  TiltMotor3: *tiltstage                                                             
  ZStage:
    com:                                                       # shares communication address with `TiltStage`
      address: FPGA    
    spum: 262                                                                   # Steps Per Micron to convert from stage steps to real world distance, used in `custom_roi_factory`
    step: 235                                                                   # steps between z planes used in microscope z-stack routiness based on Nyquist sampling
    position:
      min_val: 1000
      max_val: 65000
      units: steps
    velocity: 
      min_val: 0.1
      max_val: 5
      units: "mm/s"
    focus_start: 2000
    focus_stop: 62000
  RedLaser: 
    com:
      baudrate: 9600
      timeout: 1
      address: IL000007A
      prefix: ""
      suffix: "\r"  
    power: &red_laser                                                         # &red_laser anchor for future reference
      min_val: 0
      max_val: 400
      units: mW
  GreenLaser: 
    com:
      baudrate: 9600
      timeout: 1
      address: IL000006A
      prefix: ""
      suffix: "\r"  
    power: &green_laser                                                         # &green_laser anchor for future reference
      min_val: 0
      max_val: 400 
      units: mW
  TemperatureControllerA: &fc_temp                                              # &fc_temp anchor for future reference
    address: TiltStage
    temperature:
      min_val: 4
      max_val: 60
      units: C
  TemperatureControllerB: *fc_temp                                              # reference settings using anchor from `TemperatureControllerB`
  Shutter:
    com:
      address: FPGA
  EmissionFilter:
    com:
      address: FPGA
    filter: &emission_filter
      valid_list: {'in':'I', 'out':'O'}
  RedFilterWheel: 
    com: FPGA
    filter: &red_filter_wheel                                                   # &red_filter_wheel anchor for future reference
      valid_list: {'home':0, '4.0':36, '2.4':71, '0.2':-107, 'open':143, '1.0':107, '0.6':-36, '0.5':-71}
  GreenFilterWheel: 
    com: FPGA
    filter: &green_filter_wheel                                                 # &green_filter_wheel anchor for future reference
      valid_list: {'home':0, '4.5':-36, '3.8':-71, '3.5':-107, 'open':143, '1.0':107, '2.0':71, '4.0':36}          
# Extra validation parameters for stage beyond X, Y, Z 
# Should align with stage table in default.toml
  stage: 
    tilt1: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
    tilt2: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
    tilt3: *tiltposition                                                        # reference settings using anchor from position of `TiltStage1`
# Custom validation parameters for optical settings 
# used during imaging, focusing, or exposing 
# Should align with optics table in default.toml
  optics:
    power:
      green: *green_laser                                                       # reference settings using anchor from power of `redLaser`
      red: *red_laser                                                           # reference settings using anchor from power of `greenLaser`
    exposure: 
      Camera0: *camera_exposure                                                 # reference settings using anchor from exposure of `Camera0`
      Camera1: *camera_exposure                                                 # reference settings using anchor from exposure of `Camera1`
    filter: 
      green: *green_filter_wheel                                                # reference settings using anchor from filter of `greenFilterWheel`
      red: *red_filter_wheel                                                    # reference settings using anchor from filter of `redFilterWheel`
      emission: *emission_filter

